/**
 * 图标常量与元数据 — ICONS 图标名映射、Widget/Setting 图标尺寸注册。
 */
export const ICONS = {
  // widget icons
  keyboardCommon: 'ic:outline-keyboard-alt',
  bookmarkKeyboard: 'ic:twotone-bookmarks',
  bookmarkFolder: 'akar-icons:grid',
  clockDigital: 'fluent-emoji-high-contrast:input-numbers',
  clockAnalog: 'grommet-icons:clock',
  clockFlip: 'mdi:card-text-outline',
  clockNeon: 'mdi:television-ambient-light',
  date: 'system-uicons:calendar-date',
  calendar: 'uiw:date',
  yearProgress: 'lets-icons:time-progress',
  search: 'fluent:search-square-24-regular',
  weather: 'mdi:weather-cloudy',
  memo: 'material-symbols:note-alt-outline',
  news: 'majesticons:newspaper-line',
  newsArrowUp: 'ic:round-keyboard-arrow-up',
  newsArrowDown: 'ic:round-keyboard-arrow-down',
  countdown: 'mdi:timer-outline',
  countdownPlay: 'mdi:play',
  countdownPause: 'mdi:pause',
  countdownRestore: 'mdi:restore',
  countdownSpinUp: 'mdi:chevron-up',
  countdownSpinDown: 'mdi:chevron-down',
  chevronUp: 'mdi:chevron-up',
  chevronDown: 'mdi:chevron-down',
  chevronRight: 'mdi:chevron-right',
  refresh: 'mdi:refresh',
  shuffle: 'mdi:shuffle',
  // setting__label
  calendarHoliday: 'mdi:calendar-star',
  keyboardCommand: 'ic:twotone-keyboard-command-key',
  keyboardNameplate: 'mdi:label-outline',
  calendarToday: 'mdi:calendar-today',
  calendarRest: 'mdi:bed',
  calendarWork: 'mdi:briefcase-outline',
  neonTimeColors: 'mdi:palette-outline',
  neonFrameColors: 'mdi:border-all-variant',
  yearProgressLeftText: 'mdi:format-text',
  yearProgressRightBlock: 'mdi:view-grid-outline',
  keyboardLabel: 'mdi:keyboard-outline',
  keyboardShellLabel: 'ri:terminal-line',
  keyboardPlateLabel: 'mdi:layers-outline',
  keyboardKeycapLabel: 'mdi:keyboard-variant',
  // common
  loading: 'eos-icons:loading',
  settings: 'ion:settings-outline',
  focus: 'ri:focus-2-line',
  dragDrop: 'tabler:drag-drop',
  fullscreen: 'dashicons:fullscreen-alt',
  sponsor: 'ci:coffee-togo',
  preview: 'fe:picture',
  edit: 'uil:edit',
  check: 'ic:outline-check',
  checkCircle: 'ic:outline-check-circle',
  info: 'ix:about',
  imageSquare: 'ph:image-square',
  zoomIn: 'tdesign:zoom-in',
  downloadFill: 'ri:download-2-fill',
  favorite: 'mi:favorite',
  favoriteLine: 'clarity:favorite-line',
  favoriteSolid: 'clarity:favorite-solid',
  deleteBin: 'ri:delete-bin-6-line',
  dockLeft: 'material-symbols:dock-to-left',
  dockBottom: 'material-symbols:dock-to-bottom',
  selectFinger: 'mingcute:finger-press-line',
  currentLocation: 'tabler:current-location',
  add: 'ic:outline-add',
  ban: 'ion:ban',
  save: 'mingcute:save-2-line',
  questionBold: 'ph:question-bold',
  tune: 'mdi:tune',
  palette: 'mdi:palette-outline',
  resize: 'mdi:resize',
  // about & info
  bookOutline: 'material-symbols:book-2-outline',
  devGuideOutline: 'material-symbols:developer-guide-outline-rounded',
  newReleases: 'ic:outline-new-releases',
  feedbackMsg: 'bx:message-rounded-dots',
  thumbsUp: 'ph:thumbs-up-bold',
  githubLogo: 'carbon:logo-github',
  emailOutline: 'mdi:email-outline',
  // general actions
  importFile: 'uil:import',
  exportFile: 'uil:export',
  clearOutlined: 'ant-design:clear-outlined',
  restoreTwotone: 'ic:twotone-restore',
  // draft tool
  expandLess: 'ic:round-expand-less',
  trash: 'tabler:trash',
  trashX: 'tabler:trash-x',
  // weather widget
  warning: 'vaadin:warning',
  closeCircleLine: 'ri:close-circle-line',
  temp: 'raphael:temp',
  temperatureFeelsLike: 'carbon:temperature-feels-like',
  plusMinusBold: 'ph:plus-minus-bold',
  air: 'entypo:air',
  humidity: 'carbon:humidity',
  windyFill: 'ri:windy-fill',
  pm25: 'mdi:air-filter',
  uvIndex: 'mdi:weather-sunny-alert',
  sunrise: 'ph:sun-horizon-bold',
  sunset: 'ph:moon-stars-bold',
  // search widget
  searchAction: 'il:search',
  // calendar widget
  angleLeft: 'fa-solid:angle-left',
  angleRight: 'fa-solid:angle-right',
  arrowBackward: 'si-glyph:arrow-backward',
  // bookmark
  resizeHeight: 'cil:resize-height',
  addSolid: 'zondicons:add-solid',
  keyboardCmdKey: 'ic:twotone-keyboard-command-key',
  openInNew: 'material-symbols:open-in-new',
  bookmarkPlus: 'lucide:bookmark-plus',
  link: 'mdi:link-variant',
  text: 'mdi:format-text',
  folderOutline: 'ic:outline-folder',
  arrowBackRounded: 'material-symbols:arrow-back-rounded',
  record: 'fluent:record-12-regular',
  stop: 'fluent:record-stop-12-regular',
  close: 'mdi:close',
  faceSadCry: 'fa6-regular:face-sad-cry',
}

export const COMMAND_ICONS = {
  // 页面滚动
  scrollUp: 'material-symbols:arrow-upward-alt-rounded',
  scrollDown: 'material-symbols:arrow-downward-alt-rounded',
  scrollLeft: 'material-symbols:arrow-left-alt-rounded',
  scrollRight: 'material-symbols:arrow-right-alt-rounded',
  scrollPageUp: 'material-symbols:arrow-circle-up-outline',
  scrollPageDown: 'material-symbols:arrow-circle-down-outline',
  scrollToTop: 'tabler:arrow-bar-to-up',
  scrollToBottom: 'tabler:arrow-bar-to-down',
  scrollToLeft: 'tabler:arrow-bar-to-left',
  scrollToRight: 'tabler:arrow-bar-to-right',
  // 标签页
  moveTabLeft: 'mdi:arrow-left-bold',
  moveTabRight: 'mdi:arrow-right-bold',
  nextTab: 'mdi:skip-next',
  prevTab: 'mdi:skip-previous',
  firstTab: 'mdi:page-first',
  lastTab: 'mdi:page-last',
  goBack: 'material-symbols:keyboard-double-arrow-left',
  goForward: 'material-symbols:keyboard-double-arrow-right',
  goHome: 'mdi:home',
  lastUsedTab: 'material-symbols:swap-horiz',
  switchToPinnedTab: 'mdi:pin-outline',
  newTab: 'mdi:plus-box-outline',
  newTabAfter: 'mdi:plus-box-multiple-outline',
  closeTab: 'mdi:close',
  toggleTabPinned: 'mdi:pin',
  toggleTabMute: 'mdi:volume-mute',
  duplicateTab: 'mdi:content-duplicate',
  // 窗口操作
  newWindow: 'lucide:app-window',
  newIncognito: 'mdi:incognito',
  moveTabToNextWindow: 'mdi:arrow-bottom-right-bold-box-outline',
  moveToNewWindow: 'clarity:pop-out-line',
  moveWindowToNextDisplay: 'lucide:monitor',
  closeWindow: 'mdi:window-close',
  // 批量关闭
  closeLeftTabs: 'mdi:arrow-left-bold-box-outline',
  closeRightTabs: 'mdi:arrow-right-bold-box-outline',
  closeDuplicateTabs: 'mdi:tab-minus',
  closeOtherTabs: 'mdi:tab-remove',
  mergeAllWindows: 'lucide:combine',
  // 标签组
  groupCurrentTab: 'mdi:view-grid-plus-outline',
  ungroupCurrentTab: 'mdi:ungroup',
  toggleGroupCollapse: 'mdi:unfold-more-horizontal',
  closeGroupTabs: 'mdi:grid-off',
  // 页面操作
  copyPageUrl: 'mdi:link-variant-plus',
  copyPageTitle: 'tabler:text-recognition',
  reopenClosedTab: 'ic:round-restore',
  reloadPage: 'mdi:refresh',
  reloadAllTabs: 'tdesign:refresh',
  reloadAllTabsAllWindows: 'uil:refresh',
  // NaiveTab 页面控制
  toggleFocusMode: 'ri:focus-2-line',
  toggleDragMode: 'tabler:drag-drop',
  toggleSettingDrawer: 'ion:settings-outline',
  switchBookmarkLayer: 'material-symbols:layers-outline',
}

export type WidgetIconMeta = {
  iconName: string
  widgetSize: number
}

export type SettingIconMeta = {
  iconName: string
  settingSize: number
}

export const WIDGET_ICON_META: Record<WidgetCodes, WidgetIconMeta> = {
  keyboardBookmark: { iconName: ICONS.bookmarkKeyboard, widgetSize: 33 },
  bookmarkFolder: { iconName: ICONS.bookmarkFolder, widgetSize: 30 },
  clockDigital: { iconName: ICONS.clockDigital, widgetSize: 32 },
  clockAnalog: { iconName: ICONS.clockAnalog, widgetSize: 30 },
  clockFlip: { iconName: ICONS.clockFlip, widgetSize: 30 },
  clockNeon: { iconName: ICONS.clockNeon, widgetSize: 30 },
  date: { iconName: ICONS.date, widgetSize: 35 },
  calendar: { iconName: ICONS.calendar, widgetSize: 28 },
  yearProgress: { iconName: ICONS.yearProgress, widgetSize: 34 },
  search: { iconName: ICONS.search, widgetSize: 40 },
  weather: { iconName: ICONS.weather, widgetSize: 35 },
  memo: { iconName: ICONS.memo, widgetSize: 35 },
  news: { iconName: ICONS.news, widgetSize: 30 },
  countdown: { iconName: ICONS.countdown, widgetSize: 32 },
}

export const SETTING_ICON_META: Record<settingPanes, SettingIconMeta> = {
  general: { iconName: ICONS.settings, settingSize: 18 },
  focusMode: { iconName: ICONS.focus, settingSize: 18 },
  keyboardCommon: { iconName: ICONS.keyboardCommon, settingSize: 18 },
  keyboardCommand: { iconName: ICONS.keyboardCommand, settingSize: 18 },
  keyboardBookmark: { iconName: ICONS.bookmarkKeyboard, settingSize: 18 },
  bookmarkFolder: { iconName: ICONS.bookmarkFolder, settingSize: 18 },
  clockDate: { iconName: ICONS.clockAnalog, settingSize: 17 },
  calendar: { iconName: ICONS.calendar, settingSize: 16 },
  yearProgress: { iconName: ICONS.yearProgress, settingSize: 18 },
  search: { iconName: ICONS.search, settingSize: 19 },
  weather: { iconName: ICONS.weather, settingSize: 19 },
  memo: { iconName: ICONS.memo, settingSize: 18 },
  news: { iconName: ICONS.news, settingSize: 18 },
  countdown: { iconName: ICONS.countdown, settingSize: 18 },
  aboutSponsor: { iconName: ICONS.sponsor, settingSize: 19 },
  aboutIndex: { iconName: ICONS.info, settingSize: 19 },
}
