export { default as ColorField } from './ColorField.vue'
export { default as FontField } from './FontField.vue'
export { default as SelectFont } from './SelectFont.vue'
export { default as NumberField } from './NumberField.vue'
export { default as SwitchField } from './SwitchField.vue'
export { default as ToggleColorField } from './ToggleColorField.vue'
