// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackgroundImg: typeof import('./components/BackgroundImg.vue')['default']
    BaseComponentSetting: typeof import('./components/form/BaseComponentSetting.vue')['default']
    MoveableComponentWrap: typeof import('./components/moveable/MoveableComponentWrap.vue')['default']
    MoveableElementDrawer: typeof import('./components/moveable/MoveableElementDrawer.vue')['default']
    MoveableGuideLine: typeof import('./components/moveable/MoveableGuideLine.vue')['default']
    RightClickMenu: typeof import('./components/RightClickMenu.vue')['default']
    SponsorModal: typeof import('./components/modal/SponsorModal.vue')['default']
    Tips: typeof import('./components/form/Tips.vue')['default']
    UserGuideModal: typeof import('./components/modal/UserGuideModal.vue')['default']
    WhatsNewModal: typeof import('./components/modal/WhatsNewModal.vue')['default']
  }
}

export {}
