import { isMacOS } from '@/env'

export const hhkb: TKeyboardDefinition = {
  id: 'hhkb',
  name: 'HHKB',
  keys: [
    {
      code: 'Escape',
      x: 0,
      y: 0,
      w: 1,
      label: isMacOS ? 'esc' : 'Esc',
      textAlign: 'left',
    },
    { code: 'Digit1', x: 1, y: 0 },
    { code: 'Digit2', x: 2, y: 0 },
    { code: 'Digit3', x: 3, y: 0 },
    { code: 'Digit4', x: 4, y: 0 },
    { code: 'Digit5', x: 5, y: 0 },
    { code: 'Digit6', x: 6, y: 0 },
    { code: 'Digit7', x: 7, y: 0 },
    { code: 'Digit8', x: 8, y: 0 },
    { code: 'Digit9', x: 9, y: 0 },
    { code: 'Digit0', x: 10, y: 0 },
    { code: 'Minus', x: 11, y: 0 },
    { code: 'Equal', x: 12, y: 0 },
    { code: 'Backslash', x: 13, y: 0, w: 1 },
    { code: 'Backquote', x: 14, y: 0 },
    // Row 1
    {
      code: 'Tab',
      x: 0,
      y: 1,
      w: 1.5,
      label: isMacOS ? 'tab' : 'Tab',
      textAlign: 'left',
    },
    { code: 'KeyQ', x: 1.5, y: 1 },
    { code: 'KeyW', x: 2.5, y: 1 },
    { code: 'KeyE', x: 3.5, y: 1 },
    { code: 'KeyR', x: 4.5, y: 1 },
    { code: 'KeyT', x: 5.5, y: 1 },
    { code: 'KeyY', x: 6.5, y: 1 },
    { code: 'KeyU', x: 7.5, y: 1 },
    { code: 'KeyI', x: 8.5, y: 1 },
    { code: 'KeyO', x: 9.5, y: 1 },
    { code: 'KeyP', x: 10.5, y: 1 },
    { code: 'BracketLeft', x: 11.5, y: 1 },
    { code: 'BracketRight', x: 12.5, y: 1 },
    {
      code: 'Backspace',
      x: 13.5,
      y: 1,
      w: 1.5,
      label: isMacOS ? 'delete' : 'Delete',
      textAlign: 'left',
    },
    // Row 2
    {
      code: 'ControlLeft',
      x: 0,
      y: 2,
      w: 1.75,
      label: isMacOS ? 'control' : 'Control',
      textAlign: 'left',
    },
    { code: 'KeyA', x: 1.75, y: 2 },
    { code: 'KeyS', x: 2.75, y: 2 },
    { code: 'KeyD', x: 3.75, y: 2 },
    { code: 'KeyF', x: 4.75, y: 2 },
    { code: 'KeyG', x: 5.75, y: 2 },
    { code: 'KeyH', x: 6.75, y: 2 },
    { code: 'KeyJ', x: 7.75, y: 2 },
    { code: 'KeyK', x: 8.75, y: 2 },
    { code: 'KeyL', x: 9.75, y: 2 },
    { code: 'Semicolon', x: 10.75, y: 2 },
    { code: 'Quote', x: 11.75, y: 2 },
    {
      code: 'Enter',
      x: 12.75,
      y: 2,
      w: 2.25,
      label: isMacOS ? 'return' : 'Return',
      textAlign: 'left',
    },
    // Row 3
    {
      code: 'ShiftLeft',
      x: 0,
      y: 3,
      w: 2.25,
      label: isMacOS ? 'shift' : 'Shift',
      textAlign: 'left',
    },
    { code: 'KeyZ', x: 2.25, y: 3 },
    { code: 'KeyX', x: 3.25, y: 3 },
    { code: 'KeyC', x: 4.25, y: 3 },
    { code: 'KeyV', x: 5.25, y: 3 },
    { code: 'KeyB', x: 6.25, y: 3 },
    { code: 'KeyN', x: 7.25, y: 3 },
    { code: 'KeyM', x: 8.25, y: 3 },
    { code: 'Comma', x: 9.25, y: 3 },
    { code: 'Period', x: 10.25, y: 3 },
    { code: 'Slash', x: 11.25, y: 3 },
    { code: 'ShiftRight', x: 12.25, y: 3, w: 1.75, textAlign: 'left' },
    { code: 'Fn', x: 14, y: 3, w: 1 },
    // Row 4
    {
      code: 'MetaLeft',
      x: 1.5,
      y: 4,
      w: 1,
      label: isMacOS ? '⌘' : 'Win',
      textAlign: 'left',
    },
    {
      code: 'AltLeft',
      x: 2.5,
      y: 4,
      w: 1.5,
      label: isMacOS ? '⌥' : 'Alt',
      textAlign: 'left',
    },
    { code: 'Space', x: 4, y: 4, w: 6 },
    {
      code: 'AltRight',
      x: 10,
      y: 4,
      w: 1.5,
      label: isMacOS ? '⌥' : 'Alt',
      textAlign: 'left',
    },
    {
      code: 'MetaRight',
      x: 11.5,
      y: 4,
      w: 1,
      label: isMacOS ? '⌘' : 'Win',
      textAlign: 'left',
    },
  ],
  spaceVariants: {
    space1: [{ code: 'Space', w: 6 }],
    space2: [
      { code: 'Space', w: 3 },
      { code: 'SpaceSplit1', w: 3 },
    ],
    space3: [
      { code: 'Space', w: 2 },
      { code: 'SpaceSplit1', w: 2 },
      { code: 'SpaceSplit2', w: 2 },
    ],
  },
}
